- name: Create AEM initd service file.
  template:
    src: "{{ aem_cms_sysvinit_service_template }}"
    dest: "/etc/init.d/{{ aem_cms_service_name }}"
    mode: "0755"

- name: Enable AEM service.
  service:
    name: "{{ aem_cms_service_name }}"
    enabled: yes

- block:

  - name: Set nofile ulimit for AEM user.
    template:
      src: limits.conf.j2
      dest: "/etc/security/limits.d/{{ aem_cms_user }}.conf"

  - name: Enable pam_limits module for su.
    lineinfile:
      dest: "/etc/pam.d/su"
      line: "session required pam_limits.so"
      regexp: "#?\\s*session\\s+required\\s+pam_limits.so"

  when: aem_cms_limit_nofile