---
- name: Create AEM initd service file.
  ansible.builtin.template:
    src: "{{ aem_cms_sysvinit_service_template }}"
    dest: "/etc/init.d/{{ aem_cms_service_name }}"
    mode: "0755"

- name: Enable AEM service.
  ansible.builtin.service:
    name: "{{ aem_cms_service_name }}"
    enabled: true

- name: Configure AEM nofile limits.
  when: aem_cms_limit_nofile
  block:

    - name: Set nofile ulimit for AEM user.
      ansible.builtin.template:
        src: limits.conf.j2
        dest: "/etc/security/limits.d/{{ aem_cms_user }}.conf"
        mode: "0644"

    - name: Enable pam_limits module for su.
      ansible.builtin.lineinfile:
        dest: "/etc/pam.d/su"
        line: "session required pam_limits.so"
        regexp: "#?\\s*session\\s+required\\s+pam_limits.so"
        mode: "0644"
