---
- name: Install AEM package.
  ansible.builtin.package:
    name: "{{ aem_cms_package }}"
    state: present

- name: Copy AEM quickstart to download folder.
  ansible.builtin.copy:
    src: "{{ aem_cms_package_home }}/{{ aem_cms_quickstart_name }}"
    dest: "{{ aem_cms_download_path }}"
    remote_src: true
    owner: "{{ aem_cms_user }}"
    group: "{{ aem_cms_group }}"
    mode: "0640"

- name: Remove AEM package.
  ansible.builtin.package:
    name: "{{ aem_cms_package }}"
    state: absent
