---
name: Release

permissions:
  contents: read

'on':
  release:
    types:
      - published

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a new import on Galaxy.
        uses: robertdebock/galaxy-action@7d89099e09f4385ec4b53eb58c0d120f1ad806dd # 1.2.1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
